/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NullAgentRouteImport } from './routes/null-agent'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PackagesIndexRouteImport } from './routes/packages/index'
import { Route as PackagesSlugRouteImport } from './routes/packages/$slug'

const NullAgentRoute = NullAgentRouteImport.update({
  id: '/null-agent',
  path: '/null-agent',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesIndexRoute = PackagesIndexRouteImport.update({
  id: '/packages/',
  path: '/packages/',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesSlugRoute = PackagesSlugRouteImport.update({
  id: '/packages/$slug',
  path: '/packages/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/null-agent': typeof NullAgentRoute
  '/packages/$slug': typeof PackagesSlugRoute
  '/packages/': typeof PackagesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/null-agent': typeof NullAgentRoute
  '/packages/$slug': typeof PackagesSlugRoute
  '/packages': typeof PackagesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/null-agent': typeof NullAgentRoute
  '/packages/$slug': typeof PackagesSlugRoute
  '/packages/': typeof PackagesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/null-agent' | '/packages/$slug' | '/packages/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/null-agent' | '/packages/$slug' | '/packages'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/null-agent'
    | '/packages/$slug'
    | '/packages/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  NullAgentRoute: typeof NullAgentRoute
  PackagesSlugRoute: typeof PackagesSlugRoute
  PackagesIndexRoute: typeof PackagesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/null-agent': {
      id: '/null-agent'
      path: '/null-agent'
      fullPath: '/null-agent'
      preLoaderRoute: typeof NullAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages/': {
      id: '/packages/'
      path: '/packages'
      fullPath: '/packages/'
      preLoaderRoute: typeof PackagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages/$slug': {
      id: '/packages/$slug'
      path: '/packages/$slug'
      fullPath: '/packages/$slug'
      preLoaderRoute: typeof PackagesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  NullAgentRoute: NullAgentRoute,
  PackagesSlugRoute: PackagesSlugRoute,
  PackagesIndexRoute: PackagesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
